# Generated by Django 5.1.15 on 2026-08-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='stage1_claude_output',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='stage2_openai_output',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='stage3_gemini_output',
        ),
        migrations.AddField(
            model_name='analysis',
            name='run_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
