# Generated by Django 5.1.15 on 2026-08-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_analysis_stage1_claude_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='tokens_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
